name: Validate OS

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Operating System'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - ubuntu-latest
          - windows-latest
          - macos-latest
          - ubuntu-22.04

jobs:
  validate-os:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show OS Info
        run: |
          echo "Running on OS:"
          uname -a || ver

      - name: Print Environment Info
        run: |
          echo "Operating System: $RUNNER_OS"
          echo "Home directory: $HOME"
  build:
    runs-on: ${{ inputs.os }}
    needs: validate-os
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Project
        run: |
          echo "Building project on OS:"
          uname -a || ver
          echo "Build completed successfully."    
  run:
    runs-on: ${{ inputs.os }}
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Tests
        run: |
          echo "Running tests on OS:"
          uname -a || ver
          echo "Tests completed successfully."
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results   
