name: Validate OS

on:
  inputs:
    os:
      description: 'Operating System'
      required: true
      default: 'ubuntu-latest'
      type: choice
      options:
        - ubuntu-latest
        - windows-latest
        - macos-latest
        - ubuntu-22.04

jobs:
  validate-os:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show OS Info
        run: |
          echo "Running on OS:"
          uname -a || ver

      - name: Print Environment Info
        run: |
          echo "Operating System: $RUNNER_OS"
          echo "Home directory: $HOME"
